const NG_APP_CLIENT_ID = "YOUR CLIENT ID"
const NG_APP_API_URL = "CHOREO API URL"
const NG_APP_AUTHORITY_URL = "ASGARDEO AUTHORITY URL"
const NG_APP_WELLKNOWN_URL = "ASGARDEO WELLKNOWN URL"

export { NG_APP_CLIENT_ID, NG_APP_API_URL, NG_APP_AUTHORITY_URL, NG_APP_WELLKNOWN_URL }