"use client"

import './globals.css'
import { SessionProvider } from "next-auth/react"


export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <meta charSet="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <title>Sample App development</title>
        </head>
            <SessionProvider>
                <body>{children}</body>
            </SessionProvider>
        </html>
    )
}
